services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: systemscape
      POSTGRES_USER: systemscape
      POSTGRES_PASSWORD: systemscape
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-lab:
    build:
      context: ../services/redis-lab
    ports:
      - "8081:8081"
    environment:
      SPRING_REDIS_HOST: redis
    depends_on:
      - redis

  rate-limiter-lab:
    build:
      context: ../services/rate-limiter-lab
    ports:
      - "8082:8082"

  load-balancer-lab:
    build:
      context: ../services/load-balancer-lab
    ports:
      - "8083:8083"

  api-gateway:
    build:
      context: ../apps/api-gateway
    ports:
      - "8090:8080"
    environment:
      REDIS_LAB_URL: http://redis-lab:8081
    depends_on:
      - redis-lab

  web:
    build:
      context: ../apps/web
      args:
        NEXT_PUBLIC_REDIS_LAB_URL: http://localhost:8081
        NEXT_PUBLIC_RATE_LIMITER_URL: http://localhost:8082
        NEXT_PUBLIC_LOAD_BALANCER_URL: http://localhost:8083
    ports:
      - "3000:3000"
    environment:
      GITHUB_ID: ${GITHUB_ID:-}
      GITHUB_SECRET: ${GITHUB_SECRET:-}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-}
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - redis-lab
      - rate-limiter-lab
      - load-balancer-lab

volumes:
  postgres_data:
